forcedotcom/soql-tooling

packages/language-server/package.json
packages/language-server/src/completion.test.ts
packages/language-server/src/completion.ts

Provide initial code completion with fields on SELECT clause
W-8432064

SOQL code completion for SELECT fields

---

packages/language-server/package.json

This bumps the version of `@salesforce/soql-language-server` to 0.2.9 so it can be published in support of the VSCode build.
@W-8431809@, @W-8432064@

publish language server 0.2.9

---

package.json
packages/language-server/package.json

VSCode has made some dodgy version changes with their latest updates that have broken our build. This PR pins us to a specific version of a dependency to work around the problem.
@W-8582993@

Fix LSP dependency

---

packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
packages/soql-builder-ui/src/modules/querybuilder/where/where.css

Moves the `.btn--disabled` rule to the CSS common file so it can be used by other components.

move rule to css common

---

packages/soql-builder-ui/src/modules/querybuilder/app/app.test.ts
packages/soql-builder-ui/src/modules/querybuilder/app/app.ts
packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.ts

This PR reduces the chattiness within the soql builder ui, causing some unwanted input field strangeness, where characters are suddenly removed as i type.
@W-8555599@
Notice as i'm typing into the input, adding or removing characters, multiple characters keep getting added/removed suddenly.
Notice as I'm typing into the input, adding or removing characters is smooth.

Preventing webview re-rendering when soql statement has not changed

---

packages/soql-builder-ui/src/modules/querybuilder/app/app.html
packages/soql-builder-ui/src/modules/querybuilder/app/app.test.ts
packages/soql-builder-ui/src/modules/querybuilder/app/app.ts
packages/soql-builder-ui/src/modules/querybuilder/cssCommon/cssCommon.css
packages/soql-builder-ui/src/modules/querybuilder/header/header.html
packages/soql-builder-ui/src/modules/querybuilder/header/header.ts
packages/soql-builder-ui/src/modules/querybuilder/services/message/soqlEditorEvent.ts
packages/soql-builder-ui/src/modules/querybuilder/services/message/standaloneMessageService.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingSDK.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingSDK.ts

This PR provides the SOQL Builder UI-side function for indication that a query is running. When the `Run Query` button is pressed, the button is transformed into a disabled `Running...` button, and remains so until VSCode sends the `run_query_done` message.
@W-8207738@

Disabled 'Running...' button while query running

---

packages/language-server/src/completion.test.ts
packages/language-server/src/completion.ts
packages/language-server/src/completion/SoqlCompletionErrorStrategy.ts
packages/language-server/src/completion/SoqlQueryExtractor.ts

Add basic code-completion for ORDER BY.
Depends on https://github.com/forcedotcom/salesforcedx-vscode/pull/2792
Also:
* New implementation for extracting data from query (like SObject name),
* More robust in case of parsing errors (uses custom ANTLR Error Strategy)
* Better handling of nested queries
* Better handling of incomplete queries (nested or not)
* New completions: FOR, OFFSET, LIMIT, ORDER BY, GROUP BY, WITH, WHERE,
UPDATE TRACKING, UPDATE VIEWSTAT, COUNT(...), TYPEOF, DISTANCE
* Refactoring: Extract methods. Move class to new file. Remove old code
W-8432316

Add basic code-completion for ORDER BY and other improvements

---

packages/soql-builder-ui/package.json
packages/soql-model/package.json
packages/soql-model/src/model/model.ts
packages/soql-model/src/serialization/deserializer.test.ts
packages/soql-model/src/serialization/deserializer.ts

This PR disables WHERE in the soql-model package since the UI is not ready yet.
@W-8657716@

Disable WHERE in model

---

packages/soql-builder-ui/package.json
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.ts

This PR address this issue that was introduced in newly published version 50.14.0.  The issue is captured here. https://github.com/forcedotcom/soql-tooling/issues/120
https://github.com/forcedotcom/soql-tooling/issues/120

Fix preview not updating when autosave is off - issue 120

---

packages/soql-builder-ui/src/modules/querybuilder/app/app.css
packages/soql-builder-ui/src/modules/querybuilder/app/app.html
packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.css

This PR will refactor the use of `x-index` for some UI components. It will also move the error overlay to the further down the DOM of the form section so that it sits on top of other siblings.

set the error overlay to be on top of all other form elements

---

packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/telemetryUtils.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/telemetryUtils.ts
packages/soql-model/src/messages/messages.ts
packages/soql-model/src/model/impl/fieldSelectionImpl.test.ts
packages/soql-model/src/model/impl/fromImpl.test.ts
packages/soql-model/src/model/impl/queryImpl.test.ts
packages/soql-model/src/model/impl/soqlModelObjectImpl.test.ts
packages/soql-model/src/model/impl/unmodeledSyntaxImpl.test.ts
packages/soql-model/src/model/impl/unmodeledSyntaxImpl.ts
packages/soql-model/src/model/model.ts
packages/soql-model/src/model/unmodeled.ts
packages/soql-model/src/model/util.test.ts
packages/soql-model/src/serialization/deserializer.test.ts
packages/soql-model/src/serialization/deserializer.ts

This PR creates human readable messages for unsupported syntax. The existing 'reason codes', formatted like `unmodeled:<soql element>`, are retained for telemetry purposes.
@W-8793969@

Human readable messages for unsupported syntax

---

packages/language-server/package.json
packages/language-server/src/completion.test.ts
packages/language-server/src/completion.ts
packages/language-server/src/soqlComments.test.ts
packages/language-server/src/soqlComments.ts
packages/language-server/src/validator.test.ts
packages/language-server/src/validator.ts
packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.ts
packages/soql-model/src/model/impl/headerCommentsImpl.ts
packages/soql-model/src/model/impl/index.ts
packages/soql-model/src/model/impl/queryImpl.ts
packages/soql-model/src/model/model.ts
packages/soql-model/src/serialization/deserializer.test.ts
packages/soql-model/src/serialization/deserializer.ts
packages/soql-model/src/serialization/serializer.test.ts
packages/soql-model/src/serialization/soqlComments.test.ts
packages/soql-model/src/serialization/soqlComments.ts

Add support for line comments at the top of SOQL files.
NOTE!: syntax highlighting covered separately.
https://user-images.githubusercontent.com/152839/106056947-fe8abf00-60cd-11eb-8857-92d53c3eaa80.mov
Covers:
* The soql model
* The Builder (UI)
* LSP: text completion
* LSP: local syntax validation
* LSP: remote syntax validation
W-8611529

Add support for line comments ( `//` ) at the top of SOQL files

---

packages/soql-builder-ui/src/modules/querybuilder/app/app.ts
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.test.ts
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts

This fixes 2 bugs.
1. The error that blocks the soql builder if the soql query is empty
2. The error tooltips do not clear when sobject is changed.
@W-8827780@
https://user-images.githubusercontent.com/599418/106809798-5757db80-6629-11eb-9bd4-f3d376307691.mov
https://user-images.githubusercontent.com/599418/106809781-532bbe00-6629-11eb-91ad-f1fb07564a01.mov

Clear tooltip when object changes, fix empty soql statement error blocker

---

packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.test.ts
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts

When there is only one condition in the Filter section of the SOQL builder, and it is removed with the X button, the condition inputs should be cleared. This should be triggered when the app externally sets the condition to the default condition template value (no field, '=' operator, no value). The condition is set appropriately, but none of the display values that were being tracked in order to trigger re-rendering of the component. This PR adds a `@track` annotation to the `_criteriaDisplayValue` to force the component to render when the condition is set.
@W-8827875@

Track to force render on condition change - fix rebase conflict

---

packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.test.ts
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts

This PR fixes a bug in the multi-value input handler.  Such that the user is in the middle of typing a comma separated list of values, if the string ends in a comma and optional space(s), then the handler does not trigger a change event.
BEFORE
https://user-images.githubusercontent.com/599418/106939053-fdb0e900-66dc-11eb-8815-72fd5d10a890.mov
AFTER
https://user-images.githubusercontent.com/599418/106939017-effb6380-66dc-11eb-8a0c-282832ddcd08.mov
@W-8850622@

do not send event when user still adding input'

---

packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.html

This PR will call the selection event handler each time a new fields is selected in the custom select component. It seems this was just forgotten about when I switched out the standard <select> for the new component.
#175 #172

BUG FIX: Fire option selection event with field selection

---

packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.test.ts
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.ts

When the user clicks the X on the last modifier group, the tooltip error needs to be cleared.
@W-8827780@
BEFORE
https://user-images.githubusercontent.com/599418/107076046-3073e380-67a8-11eb-81f5-03e706d3da42.mov
AFTER
https://user-images.githubusercontent.com/599418/107076064-37025b00-67a8-11eb-8e53-49eb04db8973.mov

clear tooltip error when X is clicked

---

packages/soql-builder-ui/src/modules/querybuilder/app/app.html
packages/soql-builder-ui/src/modules/querybuilder/app/app.ts
packages/soql-builder-ui/src/modules/querybuilder/fields/fields.test.ts
packages/soql-builder-ui/src/modules/querybuilder/fields/fields.ts
packages/soql-builder-ui/src/modules/querybuilder/services/model.ts
packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/soqlUtils.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.test.ts
packages/soql-builder-ui/src/modules/querybuilder/services/toolingModelService.ts
packages/soql-model/src/model/impl/index.ts
packages/soql-model/src/model/impl/selectCountImpl.test.ts
packages/soql-model/src/model/impl/selectCountImpl.ts
packages/soql-model/src/model/model.ts
packages/soql-model/src/serialization/deserializer.test.ts
packages/soql-model/src/serialization/deserializer.ts

This PR adds COUNT() to the SOQL model and the SOQL builder fields selector. COUNT() and other fields are mutually exclusive, so when COUNT() is selected, all other selections are cleared. When some other field is selected, COUNT() is removed.
https://user-images.githubusercontent.com/55159130/107048442-f2ba8f00-6796-11eb-87cf-61c9dc7e3a63.mov
@W-8786165@

Select COUNT()

---

.github/workflows/release-soql-model.yml

Improve release action script: don't bump soql-model deps versions if it was already done on the release PR branch
N/A

build: upon release, create version bump commit only if necessary

---

packages/soql-builder-ui/package.json
packages/soql-data-view/package.json
packages/soql-model/package.json

This PR bumps versions for a manual publish so that the VSCode extension can consume them for the fix to the display and CSV export of query results.
@W-8580564@

chore: bump versions for manual publish

---

packages/soql-common/package.json

Release-As: 0.2.0
Override the version number inferred by "release-please" script

chore: override soql-common release version

---

.github/workflows/release-soql-builder-ui.yml
.github/workflows/release-soql-common.yml
.github/workflows/release-soql-data-view.yml

Configures Github action "setup-node" with an explicit npm registry url. Otherwise, it seems to not take our NPM_TOKEN.
W-8700164

build: set npm registry explicitly to fix npm publish auth errors

---

.github/workflows/release-soql-builder-ui.yml
.github/workflows/release-soql-common.yml
.github/workflows/release-soql-data-view.yml
.github/workflows/release-soql-model.yml
package.json
scripts/gh-action-bump-interdeps-versions-on-release-branch.sh
scripts/update-interdependency-versions.js

Improve release scripts to automatically keep the version inter-dependencies updated on the release PRs.
Example: On the release PR for soql-model,  the script now updates soql-builder-ui's package.json to depend on the new version.
W-8700164

build: update internal dependency versions on release PRs

---

scripts/gh-action-bump-interdeps-versions-on-release-branch.sh

Don't fail version depedencies updates when there are no release PR
W-8700164

build: only bump dependencies if there is a pending release branch

---

packages/soql-builder-ui/src/modules/querybuilder/customSelect/customSelect.html
packages/soql-builder-ui/src/modules/querybuilder/limit/limit.html
packages/soql-builder-ui/src/modules/querybuilder/whereModifierGroup/whereModifierGroup.html

In honor of today's threat model conference, i implemented the most basic of html form input controls...maxlength.  And these limits i added are just a sanity upper limit, to prevent some kinda of performance degradation with vscode or possible "network congestions / buffer overflow" issue with the api. 
The threat model here is awkward, since pasting like 10,000 characters into the where criteria would likely only cause issues with vscode.  And the salesforce soql api that we query is well protected.  At least this would prevent a HUGE api call with some giant WHERE criteria. 
These controls aren't testable, since we don't actually type into the input elements during the tests, these limits can be broken with javascript.
For the @salesforce/soql-data-view module, the Tabulator library …

fix: super simple basic input maxlength controls

---

packages/soql-builder-ui/src/modules/querybuilder/where/where.css
packages/soql-builder-ui/src/modules/querybuilder/where/where.html

This PR will fix the misaligned header labels in the where clause.
The CSS will be updated so that the general spacing of each header is controlled with flexbox but the specific alignment is controlled by styles for each header value.
Before: 
After:

fix: better align header labels with inputs
